name: Run JMeter Test

on:
  workflow_dispatch: 

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create results folder
        run: mkdir -p results

      - name: Run JMeter using Docker
        run: |
          docker run --rm \
            -v "$PWD:/jmeter" \
            -w /jmeter \
            justb4/jmeter:5.5 \
            jmeter -n \
            -t tests/JuiceShop.jmx \
            -l results/results.jtl \
            -j results/jmeter.log \
            -Jthreads=1 \
            -Jduration=120

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results
