name: Run JMeter Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create results folder
        run: mkdir -p results

      - name: Run JMeter using Docker
        run: |
          docker run --rm \
            --entrypoint jmeter \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            justb4/jmeter:5.5 \
            -n \
            -t tests/JuiceShop.jmx \
            -l results/results.jtl \
            -j results/jmeter.log \
            # -Jduration=120 \
            # -Jthreads=1

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results
